### PR TITLE
Support for compilers other than GCC, clang, MSVC

### PR DESCRIPTION
**Pull request by spth**
Currently the cbe outputs C code to be compiled with GCC, clang, MSVC.
I have improved it to emit more standard-compatible code. The output should now compile with any ISO C99 compiler, as long as alloca() is not used. In particular, the output now compiles with SDCC as long as neither alloca() nor 128-bit integers are used. To achieve this, I:
- Replaced some GCC/clang/MVC-specific stuff by standard C equivalents
- Made the output of alloca() and 128-bit integer code depend on the actual use of these features.

Philipp

P.S.: I guess it could be possible to replace all or most uses of non-standard alloca() by use of standard VLAs, but since these two have different semantics (function scope vs. block scope) it will be difficult.

### CODE REVIEW

**Comment by Ace17** [comment]
Could you please rebase your branch against mine so commit 3a232599514 doesn't appear in history?

**Comment by spth** [comment]
If you tell me how. I mostly use svn, and am not that familiar with git. In fact, I had to look up some git documentation this morning to see how to work on the standalone branch (before I was only interested in the master branches of the repositories I forked).

Philipp

**Comment by Ace17** [comment]
In your working copy:

First, be sure you're on the right branch:
$ git checkout standalone

Then, rebase:
$ git rebase master

Then, update your branch on github:
$ git push -f

**Comment by spth** [comment]
Done . But now the pull request here says that there are conflicts (unlike before).

Philipp

P.S.: Why "git rebase master"? Shouldn't I have rebased to your standalone branch or something?

**Pull request closed without merging**
